devices:
- device_type: router
  hostname: R1
  username: admin
  password: admin
  vlan_list:
  - '10'
  - '20'
  - '30'
  - '40'
  - '50'
  interfaces:
  - name: Ethernet1
    no_switchport: true
  - name: Ethernet1.40
    no_switchport: false
    encapsulation: '40'
    ipv4: 10.10.3.1/28
    ipv6: 2104::1/64
    ospf_area: 0.0.0.0
  - name: Ethernet1.50
    no_switchport: false
    encapsulation: '50'
    ipv4: 10.10.4.1/24
  - name: Ethernet2
    no_switchport: true
  - name: Ethernet2.10
    no_switchport: false
    encapsulation: '10'
    ipv4: 10.10.0.1/28
    ipv6: 2101::1/64
    ospf_area: 0.0.0.0
  - name: Ethernet2.20
    no_switchport: false
    encapsulation: '20'
    ipv4: 10.10.1.1/28
    ipv6: 2102::1/64
    ospf_area: 0.0.0.0
  - name: Ethernet2.30
    no_switchport: false
    encapsulation: '30'
    ipv6: 2103::1/64
    ospf_area: 0.0.0.0
  - name: Ethernet2.50
    no_switchport: false
    encapsulation: '50'
    ipv4: 10.10.40.1/24
  - name: Loopback0
    no_switchport: false
    ipv4: 10.0.0.1/32
  - name: Management0
    no_switchport: false
    ipv4: 172.20.20.101/24
  - name: Ethernet3
    description: This is a test
    no_switchport: true
    ipv4: 10.20.30.40/24
    ipv6: 2001::2/64
  routing:
    rip_enabled: true
    rip_networks:
    - 10.10.0.0
    - 10.10.1.0
    router_id: 10.0.0.1
    ospf_process: '10'
- device_type: router
  hostname: R2
  username: admin
  password: admin
  vlan_list:
  - '10'
  - '20'
  - '30'
  - '40'
  - '50'
  interfaces:
  - name: Ethernet1
    no_switchport: true
  - name: Ethernet1.40
    no_switchport: false
    encapsulation: '40'
    ipv4: 10.10.3.2/28
    ipv6: 2104::2/64
    ospf_area: 0.0.0.0
  - name: Ethernet1.50
    no_switchport: false
    encapsulation: '50'
    ipv4: 10.10.4.2/24
  - name: Ethernet2
    no_switchport: true
  - name: Ethernet2.10
    no_switchport: false
    encapsulation: '10'
    ipv4: 10.10.0.2/28
    ipv6: 2101::2/64
    ospf_area: 0.0.0.0
  - name: Ethernet2.20
    no_switchport: false
    encapsulation: '20'
    ipv4: 10.10.1.2/28
    ipv6: 2102::2/64
    ospf_area: 0.0.0.0
  - name: Ethernet2.30
    no_switchport: false
    encapsulation: '30'
    ipv6: 2103::2/64
    ospf_area: 0.0.0.0
  - name: Ethernet2.50
    no_switchport: false
    encapsulation: '50'
    ipv4: 10.10.40.2/24
  - name: Loopback0
    no_switchport: false
    ipv4: 10.0.0.2/32
  - name: Management0
    no_switchport: false
    ipv4: 172.20.20.102/24
  routing:
    rip_enabled: true
    rip_networks:
    - 10.10.0.0
    - 10.10.1.0
    router_id: 10.0.0.2
    ospf_process: '10'
- device_type: router
  hostname: Test
  username: test
  password: test
  vlan_list:
  - '10'
  - '20'
  - '30'
  - '40'
  - '50'
  interfaces:
  - name: Ethernet1
    description: This is a test
    no_switchport: true
    ipv4: 1.1.1.1/24
    ipv6: 2001::2/64
  - name: Ethernet2
    description: Testing again
    no_switchport: true
    ipv6: 2002::2/64
  routing:
    rip_enabled: true
    rip_networks:
    - 10.10.0.0/28
    - 10.10.1.0/28
    router_id: 1.1.1.1
    ospf_process: '10'
- device_type: router
  hostname: Test2
  username: test
  password: test
  vlan_list:
  - '10'
  - '20'
  - '30'
  - '40'
  - '50'
  interfaces:
  - name: Ethernet1
    description: This is a test
    no_switchport: true
    ipv4: 1.1.1.1/24
    ipv6: 2001::2/64
  - name: Ethernet2
    description: Testing again
    no_switchport: true
    ipv4: 2.2.2.2/24
    ipv6: 2002::2/64
  routing:
    rip_enabled: true
    rip_networks:
    - 10.10.0.0/28
    - 10.10.1.0/28
    router_id: 1.1.1.1
    ospf_process: '10'
