
---
- name: Load Variables
  include_vars:
    file: "/home/student/CSCI5840-Advanced-Network-Automation/Ansible/roles/edge_router/vars/edge_router.yml"

- name: Generate configuration files
  template: 
    src: edge_router.j2 
    dest: "/home/student/CSCI5840-Advanced-Network-Automation/Ansible/candidate_configs/{{item.hostname}}.txt"
  loop: "{{ devices | default([]) }}"
  when: devices is defined
